/* Automatically generated by configure - do not modify */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/usr/local/lib/tcc"
#endif
#ifndef CONFIG_LDDIR
# define CONFIG_LDDIR "lib64"
#endif
#define GCC_MAJOR 5
#define GCC_MINOR 3
#define TCC_VERSION "0.9.26"
